nodeLinker: node-modules

npmScopes:
    tatildekirala-inc:
        npmAlwaysAuth: true
        npmAuthToken: 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
        npmRegistryServer: 'https://npm.pkg.github.com/tatildekirala-inc'

yarnPath: .yarn/releases/yarn-3.2.2.cjs
